services:
  master:
    build: .
    command: poetry run python -m shard --mode master --port 8000
    ports:
      - "8000:8000"
      - "5050:5050"

  slave1:
    build: .
    command: poetry run python -m shard --mode slave --port 8001 --master-host master:8000
    ports:
      - "8001:8001"
    depends_on:
      - master

  slave2:
    build: .
    command: poetry run python -m shard --mode slave --port 8002 --master-host master:8000
    ports:
      - "8002:8002"
    depends_on:
      - master

  slave3:
    build: .
    command: poetry run python -m shard --mode slave --port 8003 --master-host master:8000
    ports:
      - "8003:8003"
    depends_on:
      - master

  slave4:
    build: .
    command: poetry run python -m shard --mode slave --port 8004 --master-host master:8000
    ports:
      - "8004:8004"
    depends_on:
      - master
