name: Publish Shamir Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      working-directory: package
      run: |
        poetry install 

    - name: Run tests
      working-directory: package
      run: make nox
      
    - name: Clean previous builds
      working-directory: package
      run: make clean
      
    - name: Build package
      working-directory: package
      run: make package-build
      
    - name: Publish to PyPI
      working-directory: package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: make package-upload